<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="keywords" content="<?php //echo $view->getView("Keywords")?>" />
<meta name="description" content="<?php //echo $view->getView("Description")?>" />
<meta name="author" content="<?php //echo $view->getView("Author")?>" />
<?php // echo $view->getView("Meta") ?>
<?php //echo $view->getView("Stylesheet")?>
<link rel="stylesheet" media="all" href="app/_skins/default/_css/basic.css" />
<!--[if IE]>
<link href="_skins/stylesheets/default/ie5+.css" rel="stylesheet" type="text/css">
<![endif]-->
<title>Basic Page<?php //echo $view->getView("Title")?></title>
</head>
<body>
    <header class="page-header">
        <div class="row"> Menu Top</div>
        <div class="row"> Site Logo and Branding Area </div>
        <div class="row"> Main Navigation </div>
    </header>
    <article class="container-fluid">
        <section class="row">
        <p> Welcome to Silvermedia Ghana Entertainment just go better</p>
        </section>
        <section class="row"></section>
        <section class="row"></section>
    </article>
    <footer>
        <p>&copy;Silvermedia Ghana Inc</p>
    </footer>
</body>
</html>